// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scaleway.Vpc
{
    public static class GetPrivateNetwork
    {
        /// <summary>
        /// Gets information about a private network.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Scaleway = Pulumi.Scaleway;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myName = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         Name = "foobar",
        ///     });
        /// 
        ///     var myNameAndVpcId = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         Name = "foobar",
        ///         VpcId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        ///     var myId = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         PrivateNetworkId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetPrivateNetworkResult> InvokeAsync(GetPrivateNetworkArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrivateNetworkResult>("scaleway:vpc/getPrivateNetwork:getPrivateNetwork", args ?? new GetPrivateNetworkArgs(), options.WithDefaults());

        /// <summary>
        /// Gets information about a private network.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Scaleway = Pulumi.Scaleway;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myName = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         Name = "foobar",
        ///     });
        /// 
        ///     var myNameAndVpcId = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         Name = "foobar",
        ///         VpcId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        ///     var myId = Scaleway.Vpc.GetPrivateNetwork.Invoke(new()
        ///     {
        ///         PrivateNetworkId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetPrivateNetworkResult> Invoke(GetPrivateNetworkInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivateNetworkResult>("scaleway:vpc/getPrivateNetwork:getPrivateNetwork", args ?? new GetPrivateNetworkInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPrivateNetworkArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the private network. Cannot be used with `private_network_id`.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// ID of the private network. Cannot be used with `name` and `vpc_id`.
        /// </summary>
        [Input("privateNetworkId")]
        public string? PrivateNetworkId { get; set; }

        /// <summary>
        /// The ID of the project the private network is associated with.
        /// </summary>
        [Input("projectId")]
        public string? ProjectId { get; set; }

        /// <summary>
        /// ID of the VPC in which the private network is. Cannot be used with `private_network_id`.
        /// </summary>
        [Input("vpcId")]
        public string? VpcId { get; set; }

        public GetPrivateNetworkArgs()
        {
        }
        public static new GetPrivateNetworkArgs Empty => new GetPrivateNetworkArgs();
    }

    public sealed class GetPrivateNetworkInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Name of the private network. Cannot be used with `private_network_id`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the private network. Cannot be used with `name` and `vpc_id`.
        /// </summary>
        [Input("privateNetworkId")]
        public Input<string>? PrivateNetworkId { get; set; }

        /// <summary>
        /// The ID of the project the private network is associated with.
        /// </summary>
        [Input("projectId")]
        public Input<string>? ProjectId { get; set; }

        /// <summary>
        /// ID of the VPC in which the private network is. Cannot be used with `private_network_id`.
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        public GetPrivateNetworkInvokeArgs()
        {
        }
        public static new GetPrivateNetworkInvokeArgs Empty => new GetPrivateNetworkInvokeArgs();
    }


    [OutputType]
    public sealed class GetPrivateNetworkResult
    {
        public readonly string CreatedAt;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The IPv4 subnet associated with the private network.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPrivateNetworkIpv4SubnetResult> Ipv4Subnets;
        /// <summary>
        /// The IPv6 subnets associated with the private network.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPrivateNetworkIpv6SubnetResult> Ipv6Subnets;
        public readonly bool IsRegional;
        public readonly string? Name;
        public readonly string OrganizationId;
        public readonly string? PrivateNetworkId;
        public readonly string? ProjectId;
        public readonly string Region;
        public readonly ImmutableArray<string> Tags;
        public readonly string UpdatedAt;
        public readonly string? VpcId;
        public readonly string Zone;

        [OutputConstructor]
        private GetPrivateNetworkResult(
            string createdAt,

            string id,

            ImmutableArray<Outputs.GetPrivateNetworkIpv4SubnetResult> ipv4Subnets,

            ImmutableArray<Outputs.GetPrivateNetworkIpv6SubnetResult> ipv6Subnets,

            bool isRegional,

            string? name,

            string organizationId,

            string? privateNetworkId,

            string? projectId,

            string region,

            ImmutableArray<string> tags,

            string updatedAt,

            string? vpcId,

            string zone)
        {
            CreatedAt = createdAt;
            Id = id;
            Ipv4Subnets = ipv4Subnets;
            Ipv6Subnets = ipv6Subnets;
            IsRegional = isRegional;
            Name = name;
            OrganizationId = organizationId;
            PrivateNetworkId = privateNetworkId;
            ProjectId = projectId;
            Region = region;
            Tags = tags;
            UpdatedAt = updatedAt;
            VpcId = vpcId;
            Zone = zone;
        }
    }
}
