// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Gets information about multiple Load Balancer Frontends.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumi/scaleway";
 *
 * const byLBID = scaleway.loadbalancer.getFrontends({
 *     lbId: scaleway_lb.lb01.id,
 * });
 * const byLBIDAndName = scaleway.loadbalancer.getFrontends({
 *     lbId: scaleway_lb.lb01.id,
 *     name: "tf-frontend-datasource",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getFrontends(args: GetFrontendsArgs, opts?: pulumi.InvokeOptions): Promise<GetFrontendsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scaleway:loadbalancer/getFrontends:getFrontends", {
        "lbId": args.lbId,
        "name": args.name,
        "projectId": args.projectId,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getFrontends.
 */
export interface GetFrontendsArgs {
    /**
     * The load-balancer ID this frontend is attached to. frontends with a LB ID like it are listed.
     */
    lbId: string;
    /**
     * The frontend name used as filter. Frontends with a name like it are listed.
     */
    name?: string;
    projectId?: string;
    /**
     * `zone`) The zone in which frontends exist.
     */
    zone?: string;
}

/**
 * A collection of values returned by getFrontends.
 */
export interface GetFrontendsResult {
    /**
     * List of found frontends
     */
    readonly frontends: outputs.loadbalancer.GetFrontendsFrontend[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly lbId: string;
    readonly name?: string;
    readonly organizationId: string;
    readonly projectId: string;
    readonly zone: string;
}
/**
 * Gets information about multiple Load Balancer Frontends.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumi/scaleway";
 *
 * const byLBID = scaleway.loadbalancer.getFrontends({
 *     lbId: scaleway_lb.lb01.id,
 * });
 * const byLBIDAndName = scaleway.loadbalancer.getFrontends({
 *     lbId: scaleway_lb.lb01.id,
 *     name: "tf-frontend-datasource",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getFrontendsOutput(args: GetFrontendsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFrontendsResult> {
    return pulumi.output(args).apply((a: any) => getFrontends(a, opts))
}

/**
 * A collection of arguments for invoking getFrontends.
 */
export interface GetFrontendsOutputArgs {
    /**
     * The load-balancer ID this frontend is attached to. frontends with a LB ID like it are listed.
     */
    lbId: pulumi.Input<string>;
    /**
     * The frontend name used as filter. Frontends with a name like it are listed.
     */
    name?: pulumi.Input<string>;
    projectId?: pulumi.Input<string>;
    /**
     * `zone`) The zone in which frontends exist.
     */
    zone?: pulumi.Input<string>;
}
