// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/raeumlich/pulumi-scaleway/sdk/go/scaleway/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "scaleway:vpc/gatewayNetwork:GatewayNetwork":
		r = &GatewayNetwork{}
	case "scaleway:vpc/privateNetwork:PrivateNetwork":
		r = &PrivateNetwork{}
	case "scaleway:vpc/publicGateway:PublicGateway":
		r = &PublicGateway{}
	case "scaleway:vpc/publicGatewayDHCP:PublicGatewayDHCP":
		r = &PublicGatewayDHCP{}
	case "scaleway:vpc/publicGatewayDHCPReservation:PublicGatewayDHCPReservation":
		r = &PublicGatewayDHCPReservation{}
	case "scaleway:vpc/publicGatewayIP:PublicGatewayIP":
		r = &PublicGatewayIP{}
	case "scaleway:vpc/publicGatewayIPReverseDNS:PublicGatewayIPReverseDNS":
		r = &PublicGatewayIPReverseDNS{}
	case "scaleway:vpc/publicGatewayPATRule:PublicGatewayPATRule":
		r = &PublicGatewayPATRule{}
	case "scaleway:vpc/vPC:VPC":
		r = &VPC{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/gatewayNetwork",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/privateNetwork",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGateway",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGatewayDHCP",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGatewayDHCPReservation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGatewayIP",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGatewayIPReverseDNS",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/publicGatewayPATRule",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"vpc/vPC",
		&module{version},
	)
}
