// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package loadbalancer

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/raeumlich/pulumi-scaleway/sdk/go/scaleway/internal"
)

// Gets information about multiple Load Balancer Backends.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/raeumlich/pulumi-scaleway/sdk/go/scaleway/loadbalancer"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := loadbalancer.GetBackends(ctx, &loadbalancer.GetBackendsArgs{
//				LbId: scaleway_lb.Lb01.Id,
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = loadbalancer.GetBackends(ctx, &loadbalancer.GetBackendsArgs{
//				LbId: scaleway_lb.Lb01.Id,
//				Name: pulumi.StringRef("tf-backend-datasource"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetBackends(ctx *pulumi.Context, args *GetBackendsArgs, opts ...pulumi.InvokeOption) (*GetBackendsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBackendsResult
	err := ctx.Invoke("scaleway:loadbalancer/getBackends:getBackends", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getBackends.
type GetBackendsArgs struct {
	// The load-balancer ID this backend is attached to. backends with a LB ID like it are listed.
	LbId string `pulumi:"lbId"`
	// The backend name used as filter. Backends with a name like it are listed.
	Name      *string `pulumi:"name"`
	ProjectId *string `pulumi:"projectId"`
	// `zone`) The zone in which backends exist.
	Zone *string `pulumi:"zone"`
}

// A collection of values returned by getBackends.
type GetBackendsResult struct {
	// List of found backends
	Backends []GetBackendsBackend `pulumi:"backends"`
	// The provider-assigned unique ID for this managed resource.
	Id             string  `pulumi:"id"`
	LbId           string  `pulumi:"lbId"`
	Name           *string `pulumi:"name"`
	OrganizationId string  `pulumi:"organizationId"`
	ProjectId      string  `pulumi:"projectId"`
	Zone           string  `pulumi:"zone"`
}

func GetBackendsOutput(ctx *pulumi.Context, args GetBackendsOutputArgs, opts ...pulumi.InvokeOption) GetBackendsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetBackendsResult, error) {
			args := v.(GetBackendsArgs)
			r, err := GetBackends(ctx, &args, opts...)
			var s GetBackendsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetBackendsResultOutput)
}

// A collection of arguments for invoking getBackends.
type GetBackendsOutputArgs struct {
	// The load-balancer ID this backend is attached to. backends with a LB ID like it are listed.
	LbId pulumi.StringInput `pulumi:"lbId"`
	// The backend name used as filter. Backends with a name like it are listed.
	Name      pulumi.StringPtrInput `pulumi:"name"`
	ProjectId pulumi.StringPtrInput `pulumi:"projectId"`
	// `zone`) The zone in which backends exist.
	Zone pulumi.StringPtrInput `pulumi:"zone"`
}

func (GetBackendsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBackendsArgs)(nil)).Elem()
}

// A collection of values returned by getBackends.
type GetBackendsResultOutput struct{ *pulumi.OutputState }

func (GetBackendsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBackendsResult)(nil)).Elem()
}

func (o GetBackendsResultOutput) ToGetBackendsResultOutput() GetBackendsResultOutput {
	return o
}

func (o GetBackendsResultOutput) ToGetBackendsResultOutputWithContext(ctx context.Context) GetBackendsResultOutput {
	return o
}

// List of found backends
func (o GetBackendsResultOutput) Backends() GetBackendsBackendArrayOutput {
	return o.ApplyT(func(v GetBackendsResult) []GetBackendsBackend { return v.Backends }).(GetBackendsBackendArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetBackendsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetBackendsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetBackendsResultOutput) LbId() pulumi.StringOutput {
	return o.ApplyT(func(v GetBackendsResult) string { return v.LbId }).(pulumi.StringOutput)
}

func (o GetBackendsResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetBackendsResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o GetBackendsResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetBackendsResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetBackendsResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetBackendsResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func (o GetBackendsResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v GetBackendsResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBackendsResultOutput{})
}
