// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scaleway.Instance.Outputs
{

    [OutputType]
    public sealed class GetServerPrivateNetworkResult
    {
        public readonly string MacAddress;
        public readonly string PnId;
        public readonly string Status;
        /// <summary>
        /// `zone`) The zone in which the server exists.
        /// </summary>
        public readonly string Zone;

        [OutputConstructor]
        private GetServerPrivateNetworkResult(
            string macAddress,

            string pnId,

            string status,

            string zone)
        {
            MacAddress = macAddress;
            PnId = pnId;
            Status = status;
            Zone = zone;
        }
    }
}
