// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package documentdb

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/raeumlich/pulumi-scaleway/sdk/go/scaleway/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "scaleway:documentdb/database:Database":
		r = &Database{}
	case "scaleway:documentdb/instance:Instance":
		r = &Instance{}
	case "scaleway:documentdb/privateNetworkEndpoint:PrivateNetworkEndpoint":
		r = &PrivateNetworkEndpoint{}
	case "scaleway:documentdb/privilege:Privilege":
		r = &Privilege{}
	case "scaleway:documentdb/readReplica:ReadReplica":
		r = &ReadReplica{}
	case "scaleway:documentdb/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/instance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/privateNetworkEndpoint",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/privilege",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/readReplica",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"scaleway",
		"documentdb/user",
		&module{version},
	)
}
