// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scaleway.Rdb
{
    public static class GetACL
    {
        /// <summary>
        /// Gets information about the RDB instance network Access Control List.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Scaleway = Pulumi.Scaleway;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myAcl = Scaleway.Rdb.GetACL.Invoke(new()
        ///     {
        ///         InstanceId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetACLResult> InvokeAsync(GetACLArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetACLResult>("scaleway:rdb/getACL:getACL", args ?? new GetACLArgs(), options.WithDefaults());

        /// <summary>
        /// Gets information about the RDB instance network Access Control List.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Scaleway = Pulumi.Scaleway;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myAcl = Scaleway.Rdb.GetACL.Invoke(new()
        ///     {
        ///         InstanceId = "11111111-1111-1111-1111-111111111111",
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetACLResult> Invoke(GetACLInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetACLResult>("scaleway:rdb/getACL:getACL", args ?? new GetACLInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetACLArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The RDB instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public string InstanceId { get; set; } = null!;

        /// <summary>
        /// `region`) The region in which the Database Instance should be created.
        /// </summary>
        [Input("region")]
        public string? Region { get; set; }

        public GetACLArgs()
        {
        }
        public static new GetACLArgs Empty => new GetACLArgs();
    }

    public sealed class GetACLInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The RDB instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<string> InstanceId { get; set; } = null!;

        /// <summary>
        /// `region`) The region in which the Database Instance should be created.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        public GetACLInvokeArgs()
        {
        }
        public static new GetACLInvokeArgs Empty => new GetACLInvokeArgs();
    }


    [OutputType]
    public sealed class GetACLResult
    {
        /// <summary>
        /// A list of ACLs rules (structure is described below)
        /// </summary>
        public readonly ImmutableArray<Outputs.GetACLAclRuleResult> AclRules;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string InstanceId;
        public readonly string? Region;

        [OutputConstructor]
        private GetACLResult(
            ImmutableArray<Outputs.GetACLAclRuleResult> aclRules,

            string id,

            string instanceId,

            string? region)
        {
            AclRules = aclRules;
            Id = id;
            InstanceId = instanceId;
            Region = region;
        }
    }
}
