// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Gets information about a private network.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumi/scaleway";
 *
 * const myName = scaleway.vpc.getPrivateNetwork({
 *     name: "foobar",
 * });
 * const myNameAndVpcId = scaleway.vpc.getPrivateNetwork({
 *     name: "foobar",
 *     vpcId: "11111111-1111-1111-1111-111111111111",
 * });
 * const myId = scaleway.vpc.getPrivateNetwork({
 *     privateNetworkId: "11111111-1111-1111-1111-111111111111",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getPrivateNetwork(args?: GetPrivateNetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivateNetworkResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("scaleway:vpc/getPrivateNetwork:getPrivateNetwork", {
        "name": args.name,
        "privateNetworkId": args.privateNetworkId,
        "projectId": args.projectId,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPrivateNetwork.
 */
export interface GetPrivateNetworkArgs {
    /**
     * Name of the private network. Cannot be used with `privateNetworkId`.
     */
    name?: string;
    /**
     * ID of the private network. Cannot be used with `name` and `vpcId`.
     */
    privateNetworkId?: string;
    /**
     * The ID of the project the private network is associated with.
     */
    projectId?: string;
    /**
     * ID of the VPC in which the private network is. Cannot be used with `privateNetworkId`.
     */
    vpcId?: string;
}

/**
 * A collection of values returned by getPrivateNetwork.
 */
export interface GetPrivateNetworkResult {
    readonly createdAt: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The IPv4 subnet associated with the private network.
     */
    readonly ipv4Subnets: outputs.vpc.GetPrivateNetworkIpv4Subnet[];
    /**
     * The IPv6 subnets associated with the private network.
     */
    readonly ipv6Subnets: outputs.vpc.GetPrivateNetworkIpv6Subnet[];
    readonly isRegional: boolean;
    readonly name?: string;
    readonly organizationId: string;
    readonly privateNetworkId?: string;
    readonly projectId?: string;
    readonly region: string;
    readonly tags: string[];
    readonly updatedAt: string;
    readonly vpcId?: string;
    readonly zone: string;
}
/**
 * Gets information about a private network.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as scaleway from "@pulumi/scaleway";
 *
 * const myName = scaleway.vpc.getPrivateNetwork({
 *     name: "foobar",
 * });
 * const myNameAndVpcId = scaleway.vpc.getPrivateNetwork({
 *     name: "foobar",
 *     vpcId: "11111111-1111-1111-1111-111111111111",
 * });
 * const myId = scaleway.vpc.getPrivateNetwork({
 *     privateNetworkId: "11111111-1111-1111-1111-111111111111",
 * });
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getPrivateNetworkOutput(args?: GetPrivateNetworkOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPrivateNetworkResult> {
    return pulumi.output(args).apply((a: any) => getPrivateNetwork(a, opts))
}

/**
 * A collection of arguments for invoking getPrivateNetwork.
 */
export interface GetPrivateNetworkOutputArgs {
    /**
     * Name of the private network. Cannot be used with `privateNetworkId`.
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the private network. Cannot be used with `name` and `vpcId`.
     */
    privateNetworkId?: pulumi.Input<string>;
    /**
     * The ID of the project the private network is associated with.
     */
    projectId?: pulumi.Input<string>;
    /**
     * ID of the VPC in which the private network is. Cannot be used with `privateNetworkId`.
     */
    vpcId?: pulumi.Input<string>;
}
