// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Scaleway.Loadbalancer.Outputs
{

    [OutputType]
    public sealed class GetFrontendAclResult
    {
        public readonly ImmutableArray<Outputs.GetFrontendAclActionResult> Actions;
        public readonly string CreatedAt;
        public readonly string Description;
        public readonly ImmutableArray<Outputs.GetFrontendAclMatchResult> Matches;
        /// <summary>
        /// The name of the frontend.
        /// - When using the `name` you should specify the `lb-id`
        /// </summary>
        public readonly string Name;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetFrontendAclResult(
            ImmutableArray<Outputs.GetFrontendAclActionResult> actions,

            string createdAt,

            string description,

            ImmutableArray<Outputs.GetFrontendAclMatchResult> matches,

            string name,

            string updatedAt)
        {
            Actions = actions;
            CreatedAt = createdAt;
            Description = description;
            Matches = matches;
            Name = name;
            UpdatedAt = updatedAt;
        }
    }
}
